import { useMemo, useState } from 'react'
import { Search, Plus, X, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import Status from '../components/Status.jsx'
import { initialComplaints } from '../data.js'
export default function MyComplaints(){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [selected,setSelected]=useState(null)
 const complaints=useMemo(()=>{const saved=JSON.parse(localStorage.getItem('resolvehub-complaints')||'[]');return [...saved,...initialComplaints]},[])
 const shown=complaints.filter(c=>(filter==='All'||c.status===filter)&&`${c.id} ${c.title} ${c.category}`.toLowerCase().includes(query.toLowerCase()))
 return <div className="page-stack"><div className="welcome-row"><div><div className="eyebrow">YOUR ACTIVITY</div><h1>My complaints</h1><p>Review updates and follow the progress of your reports.</p></div><Link to="/new-complaint" className="btn btn-primary"><Plus size={17}/> New complaint</Link></div><section className="panel complaints-panel"><div className="list-toolbar"><label className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by title, ID or category"/></label><div className="filter-wrap"><SlidersHorizontal size={16}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Pending</option><option>In Progress</option><option>Resolved</option></select></div></div><div className="table-wrap"><table><thead><tr><th>COMPLAINT</th><th>CATEGORY</th><th>DATE</th><th>STATUS</th><th></th></tr></thead><tbody>{shown.map(c=><tr key={c.id}><td><b>{c.title}</b><small>{c.id}</small></td><td>{c.category}</td><td>{c.date}</td><td><Status value={c.status}/></td><td><button className="view-btn" onClick={()=>setSelected(c)}>View details ↗</button></td></tr>)}</tbody></table>{shown.length===0&&<div className="empty-state"><div>⌕</div><b>No complaints found</b><p>Try a different search or submit a new complaint.</p></div>}</div><div className="table-foot">Showing {shown.length} complaint{shown.length===1?'':'s'} <span>Demo data is stored in this browser.</span></div></section>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><small>COMPLAINT DETAILS</small><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={19}/></button></div><div className="detail-id">{selected.id} <Status value={selected.status}/></div><p className="detail-description">{selected.description}</p><div className="detail-grid"><div><small>Category</small><b>{selected.category}</b></div><div><small>Date submitted</small><b>{selected.date}</b></div><div><small>Priority</small><b>{selected.priority||'Medium'}</b></div><div><small>Location</small><b>{selected.location||'Not provided'}</b></div></div><button className="btn btn-primary modal-close" onClick={()=>setSelected(null)}>Done</button></section></div>}</div>
}