import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowLeft, UploadCloud, CheckCircle2 } from 'lucide-react'
export default function NewComplaint(){
 const [form,setForm]=useState({title:'',category:'',priority:'Medium',location:'',description:''}); const [done,setDone]=useState(false); const navigate=useNavigate()
 const update=e=>setForm({...form,[e.target.name]:e.target.value})
 function submit(e){e.preventDefault();const list=JSON.parse(localStorage.getItem('resolvehub-complaints')||'[]');list.unshift({...form,id:`RH-${Math.floor(1000+Math.random()*9000)}`,date:new Date().toISOString().slice(0,10),status:'Pending'});localStorage.setItem('resolvehub-complaints',JSON.stringify(list));setDone(true)}
 if(done)return <div className="success-card"><div className="success-icon"><CheckCircle2 size={34}/></div><h1>Complaint submitted!</h1><p>Your complaint has been saved locally for this demo.</p><button className="btn btn-primary" onClick={()=>navigate('/my-complaints')}>View my complaints</button></div>
 return <div className="form-page"><Link to="/dashboard" className="back-link"><ArrowLeft size={16}/> Back to dashboard</Link><div className="page-heading"><div className="eyebrow">LET'S MAKE IT BETTER</div><h1>Submit a complaint</h1><p>Tell us what needs attention. We'll help route it to the right team.</p></div><form className="panel complaint-form" onSubmit={submit}><div className="form-section-title"><span>01</span><div><b>Issue details</b><small>Give your complaint a clear title and category.</small></div></div><div className="field"><label>Complaint title <em>*</em></label><input required name="title" value={form.title} onChange={update} placeholder="e.g. Street light not working"/></div><div className="field-row"><div className="field"><label>Category <em>*</em></label><select required name="category" value={form.category} onChange={update}><option value="">Select a category</option>{['Water Supply','Electricity','Sanitation','Roads','Public Safety','Other'].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Priority</label><select name="priority" value={form.priority} onChange={update}><option>Low</option><option>Medium</option><option>High</option></select></div></div><div className="field"><label>Location <em>*</em></label><input required name="location" value={form.location} onChange={update} placeholder="Area, street or nearby landmark"/></div><div className="field"><label>Describe the issue <em>*</em></label><textarea required rows="5" name="description" value={form.description} onChange={update} placeholder="Please share what happened, when it started, and how it affects the area..."/></div><div className="upload-box"><UploadCloud size={23}/><b>Attach supporting files</b><span>Optional · Image or document attachments (demo UI)</span><input type="file" accept="image/*,.pdf" /></div><div className="form-actions"><span><em>*</em> Required fields</span><button className="btn btn-primary" type="submit">Submit complaint <ArrowLeft className="submit-arrow" size={16}/></button></div></form></div>
}